# Generated by Django 3.1.7 on 2021-04-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='value',
            new_name='discount',
        ),
    ]
